/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author csouza
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConsulta = new javax.swing.JMenu();
        menuConsultaUsuario = new javax.swing.JMenuItem();
        consultaItemLivro = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroUsuário = new javax.swing.JMenuItem();
        itemLivroCad = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuEditarUsuário = new javax.swing.JMenuItem();
        btnEditar = new javax.swing.JMenuItem();
        menuRemover = new javax.swing.JMenu();
        menuRemoverUsuário = new javax.swing.JMenuItem();
        removerItemLivro = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuConsulta.setText("Consulta");

        menuConsultaUsuario.setText("Usuário");
        menuConsulta.add(menuConsultaUsuario);

        consultaItemLivro.setText("Livro");
        consultaItemLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaItemLivroActionPerformed(evt);
            }
        });
        menuConsulta.add(consultaItemLivro);

        jMenuBar1.add(menuConsulta);

        menuCadastro.setText("Cadastro");

        menuCadastroUsuário.setText("Usuário");
        menuCadastro.add(menuCadastroUsuário);

        itemLivroCad.setText("Livro");
        itemLivroCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLivroCadActionPerformed(evt);
            }
        });
        menuCadastro.add(itemLivroCad);

        jMenuBar1.add(menuCadastro);

        menuEditar.setText("Editar");

        menuEditarUsuário.setText("Usuário");
        menuEditar.add(menuEditarUsuário);

        btnEditar.setText("Livro");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        menuEditar.add(btnEditar);

        jMenuBar1.add(menuEditar);

        menuRemover.setText("Remover");

        menuRemoverUsuário.setText("Usuário");
        menuRemover.add(menuRemoverUsuário);

        removerItemLivro.setText("Livro");
        removerItemLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerItemLivroActionPerformed(evt);
            }
        });
        menuRemover.add(removerItemLivro);

        jMenuBar1.add(menuRemover);

        menuSair.setText("Sair");
        menuSair.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuSairMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed

    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuSairMenuSelected
        new Thread(){
           public void run(){
               new Login().setVisible(true);
               dispose();
           }
       }.start();    }//GEN-LAST:event_menuSairMenuSelected

    private void consultaItemLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaItemLivroActionPerformed
        new ConsultaLivro().setVisible(true);
    }//GEN-LAST:event_consultaItemLivroActionPerformed

    private void itemLivroCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLivroCadActionPerformed
        new CadastroLivro().setVisible(true);
    }//GEN-LAST:event_itemLivroCadActionPerformed

    private void removerItemLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerItemLivroActionPerformed
        new RemoverLivro().setVisible(true);
    }//GEN-LAST:event_removerItemLivroActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        new EditarLivro().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnEditar;
    private javax.swing.JMenuItem consultaItemLivro;
    private javax.swing.JMenuItem itemLivroCad;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroUsuário;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuConsultaUsuario;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuEditarUsuário;
    private javax.swing.JMenu menuRemover;
    private javax.swing.JMenuItem menuRemoverUsuário;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem removerItemLivro;
    // End of variables declaration//GEN-END:variables
}
